"""Service to generate a Protocol graph from a chat conversation via LLM."""

import logging
from datetime import datetime, timezone
from typing import Any, Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, Field
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.chat import ChatMessage, ChatSession
from app.models.science import Protocol, UnitOpDefinition
from app.services.ai_config import get_model

logger = logging.getLogger(__name__)


# --- Pydantic output models for structured LLM output ---


class GeneratedStep(BaseModel):
    """A single step in a generated protocol."""

    name: str = Field(description="Display name for this step")
    unit_op_name: str = Field(
        description="Name of the unit operation from the catalog"
    )
    category: str = Field(
        default="General",
        description="Category (e.g. Media Prep, Cell Culture)",
    )
    description: str = Field(default="", description="Brief description")
    duration_min: int = Field(
        default=30, description="Estimated duration in minutes"
    )
    params: dict[str, Any] = Field(
        default_factory=dict,
        description="Parameter values for this step",
    )


class GeneratedProtocol(BaseModel):
    """Complete protocol generated by the LLM."""

    name: str = Field(description="Protocol name")
    description: str = Field(default="", description="Protocol description")
    steps: list[GeneratedStep] = Field(
        description="Ordered list of protocol steps"
    )


# --- Public API ---


async def generate_protocol_from_chat(
    db: AsyncSession,
    session: ChatSession,
    project_id: UUID,
    user_id: UUID,
    protocol_name: Optional[str] = None,
) -> Protocol:
    """Generate a Protocol from a chat conversation.

    Args:
        db: Database session.
        session: The chat session with conversation history.
        project_id: Target project for the new protocol.
        user_id: User requesting the generation.
        protocol_name: Optional override name for the protocol.

    Returns:
        The created Protocol record (DRAFT status).
    """
    from app.services.chat_service import _get_message_history

    # 1. Fetch conversation history
    history = await _get_message_history(db, session.id)

    # 2. Fetch unit op catalog
    result = await db.execute(select(UnitOpDefinition))
    unit_ops = list(result.scalars().all())

    # 3. Build prompt and call LLM
    generated = await _call_generation_llm(db, history, unit_ops, org_id=session.org_id)

    # Override name if provided
    if protocol_name:
        generated.name = protocol_name

    # 4. Build graph JSONB
    graph = _build_graph(generated, unit_ops, session.id, user_id)

    # 5. Create Protocol record
    protocol = Protocol(
        name=generated.name,
        description=generated.description,
        project_id=project_id,
        status="DRAFT",
        graph=graph,
    )
    db.add(protocol)
    await db.flush()

    # 6. Append system message to chat session
    from app.models.chat import ChatMessage, ChatMessageRole

    sys_msg = ChatMessage(
        session_id=session.id,
        role=ChatMessageRole.SYSTEM,
        content=(
            f"Protocol '{generated.name}' generated as draft "
            f"in project."
        ),
    )
    db.add(sys_msg)
    await db.flush()

    return protocol


# --- Internal helpers ---


async def _call_generation_llm(
    db: AsyncSession,
    history: list[dict[str, str]],
    unit_ops: list[UnitOpDefinition],
    org_id: UUID | None = None,
) -> GeneratedProtocol:
    """Call the LLM with structured output to generate a protocol."""
    from pydantic_ai import Agent

    # Build unit op catalog string
    catalog_lines = []
    for op in unit_ops:
        schema_str = ""
        if op.param_schema and op.param_schema.get("properties"):
            props = list(op.param_schema["properties"].keys())
            schema_str = f" (params: {', '.join(props)})"
        catalog_lines.append(
            f"- {op.name} [{op.category}]{schema_str}: "
            f"{op.description or 'No description'}"
        )
    catalog = "\n".join(catalog_lines) if catalog_lines else "(empty catalog)"

    system_prompt = f"""You are a protocol design assistant for biotech Process Development.

Given a conversation between a scientist and an AI assistant, extract the discussed
procedure and generate a structured protocol.

UNIT OPERATION CATALOG (use these names when possible):
{catalog}

RULES:
1. Each step must reference a unit_op_name from the catalog when a match exists.
2. If no catalog match exists, use a descriptive name and category="General".
3. Order steps sequentially as discussed in the conversation.
4. Set reasonable durations based on the discussion or domain knowledge.
5. Extract any parameter values mentioned in the conversation.
6. Generate a concise protocol name and description summarizing the procedure."""

    # Format conversation
    conv_parts = []
    for msg in history:
        role = "User" if msg["role"] == "user" else "Assistant"
        conv_parts.append(f"{role}: {msg['content']}")
    conversation = "\n\n".join(conv_parts)

    prompt = (
        f"Based on this conversation, generate a structured protocol:\n\n"
        f"{conversation}"
    )

    model = await get_model("protocol_generation", db, org_id=org_id)
    agent = Agent(model, system_prompt=system_prompt, output_type=GeneratedProtocol)
    result = await agent.run(prompt)
    return result.output


def _build_graph(
    generated: GeneratedProtocol,
    unit_ops: list[UnitOpDefinition],
    session_id: UUID,
    user_id: UUID,
) -> dict[str, Any]:
    """Transform generated protocol into graph JSONB for the Protocol model.

    Creates a sequential horizontal layout with nodes connected by edges.
    """
    nodes: list[dict[str, Any]] = []
    edges: list[dict[str, Any]] = []

    x_start = 100
    x_increment = 300
    y_position = 200

    for i, step in enumerate(generated.steps):
        node_id = f"node-{uuid4()}"
        matched_op = _match_unit_op(step.unit_op_name, unit_ops)

        # Build param schema and merged params
        param_schema = {}
        params = dict(step.params)
        if matched_op:
            param_schema = matched_op.param_schema or {}
            params = _extract_params(step.params, param_schema)
            category = matched_op.category
            unit_op_id = str(matched_op.id)
        else:
            category = step.category
            unit_op_id = None

        node = {
            "id": node_id,
            "type": "unitOp",
            "position": {"x": x_start + i * x_increment, "y": y_position},
            "data": {
                "label": step.name,
                "unitOpId": unit_op_id,
                "category": category,
                "description": step.description,
                "duration_min": step.duration_min,
                "params": params,
                "paramSchema": param_schema,
            },
        }
        nodes.append(node)

        # Create edge to previous node
        if i > 0:
            edge = {
                "id": f"edge-{uuid4()}",
                "source": nodes[i - 1]["id"],
                "target": node_id,
            }
            edges.append(edge)

    return {
        "nodes": nodes,
        "edges": edges,
        "layout": "horizontal",
        "handleOrientation": "horizontal",
        "timeEnabled": False,
        "startTime": "08:00",
        "pixelsPerHour": 150,
        "_metadata": {
            "source": "ai_generated",
            "chat_session_id": str(session_id),
            "generated_by": str(user_id),
            "generated_at": datetime.now(timezone.utc).isoformat(),
        },
    }


def _match_unit_op(
    name: str, unit_ops: list[UnitOpDefinition]
) -> Optional[UnitOpDefinition]:
    """Match a step name to a UnitOpDefinition.

    Tries exact match first, then case-insensitive.
    """
    # Exact match
    for op in unit_ops:
        if op.name == name:
            return op

    # Case-insensitive match
    name_lower = name.lower()
    for op in unit_ops:
        if op.name.lower() == name_lower:
            return op

    return None


def _extract_params(
    step_params: dict[str, Any],
    param_schema: dict[str, Any],
) -> dict[str, Any]:
    """Merge step params with schema defaults.

    For each property in the schema, use the step param if provided,
    otherwise fall back to the schema default.
    """
    merged = {}
    properties = param_schema.get("properties", {})

    # Start with schema defaults
    for prop_name, prop_def in properties.items():
        if "default" in prop_def:
            merged[prop_name] = prop_def["default"]

    # Override with step params
    for key, value in step_params.items():
        merged[key] = value

    return merged
