"""add_processing_started_at_to_documents

Revision ID: 0f25b1927b33
Revises: a1deb5e1d9ee
Create Date: 2026-03-18 15:57:26.582367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f25b1927b33'
down_revision: Union[str, Sequence[str], None] = 'a1deb5e1d9ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'processing_started_at')
    # ### end Alembic commands ###
