"""add oauth fields to users table

Revision ID: 248af12c65f7
Revises: f231e81290bd
Create Date: 2026-04-18 23:03:25.304733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '248af12c65f7'
down_revision: Union[str, Sequence[str], None] = 'f231e81290bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oauth_provider', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('oauth_subject', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('oauth_email_verified', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_users_oauth_provider'), 'users', ['oauth_provider'], unique=False)
    op.create_unique_constraint('uq_oauth_provider_subject', 'users', ['oauth_provider', 'oauth_subject'])
    op.create_index('ix_users_oauth_provider_subject', 'users', ['oauth_provider', 'oauth_subject'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_oauth_provider_subject', 'users', type_='unique')
    op.drop_index('ix_users_oauth_provider_subject', table_name='users')
    op.drop_index(op.f('ix_users_oauth_provider'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'oauth_email_verified')
    op.drop_column('users', 'oauth_subject')
    op.drop_column('users', 'oauth_provider')
    # ### end Alembic commands ###
