"""add started_by_id to runs

Revision ID: 27058fbd07b9
Revises: ca5ce36de9cd
Create Date: 2026-03-05 23:29:51.569929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27058fbd07b9'
down_revision: Union[str, Sequence[str], None] = 'ca5ce36de9cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('started_by_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'runs', 'users', ['started_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'runs', type_='foreignkey')
    op.drop_column('runs', 'started_by_id')
    # ### end Alembic commands ###
