"""add_avatar_jobtitle_preferences_to_users

Revision ID: 39bcc5f1f3c1
Revises: ff7befb11e89
Create Date: 2026-03-07 15:54:39.160576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39bcc5f1f3c1'
down_revision: Union[str, Sequence[str], None] = 'ff7befb11e89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('job_title', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar_path', sa.String(), nullable=True))
    op.add_column('users', sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferences')
    op.drop_column('users', 'avatar_path')
    op.drop_column('users', 'job_title')
    # ### end Alembic commands ###
