"""add protocol versioning and approval

Revision ID: 4ffc79bc8a53
Revises: 634cdeb56c08
Create Date: 2026-02-20 21:26:12.028642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ffc79bc8a53'
down_revision: Union[str, Sequence[str], None] = '634cdeb56c08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protocol_versions',
    sa.Column('protocol_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('graph', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('change_summary', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_proto_ver_lookup', 'protocol_versions', ['protocol_id', 'version_number'], unique=True)
    op.add_column('projects', sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('protocols', sa.Column('status', sa.String(), server_default='DRAFT', nullable=False))
    op.add_column('protocols', sa.Column('version_number', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('protocols', 'version_number')
    op.drop_column('protocols', 'status')
    op.drop_column('projects', 'settings')
    op.drop_index('ix_proto_ver_lookup', table_name='protocol_versions')
    op.drop_table('protocol_versions')
    # ### end Alembic commands ###
