"""add_parameter_tags_to_run_images

Revision ID: 6081e54decae
Revises: 83fbf6595e21
Create Date: 2026-03-08 22:23:00.408034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6081e54decae'
down_revision: Union[str, Sequence[str], None] = '83fbf6595e21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run_images', sa.Column('parameter_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run_images', 'parameter_tags')
    # ### end Alembic commands ###
