"""add_rbac_tables

Revision ID: a82b05858eda
Revises: b7e2f3a89c12
Create Date: 2026-02-16 21:23:33.673428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a82b05858eda'
down_revision: Union[str, Sequence[str], None] = 'b7e2f3a89c12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object_permissions',
    sa.Column('principal_type', sa.String(), nullable=False),
    sa.Column('principal_id', sa.Uuid(), nullable=False),
    sa.Column('object_type', sa.String(), nullable=False),
    sa.Column('object_id', sa.Uuid(), nullable=False),
    sa.Column('permission_level', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('principal_type', 'principal_id', 'object_type', 'object_id', name='uq_object_permission')
    )
    op.create_index('ix_objperm_object', 'object_permissions', ['object_type', 'object_id'], unique=False)
    op.create_index('ix_objperm_principal', 'object_permissions', ['principal_type', 'principal_id'], unique=False)
    op.create_table('organization_members',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_org_member')
    )
    op.drop_table('run_sheets')
    op.add_column('projects', sa.Column('owner_type', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('owner_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'owner_id')
    op.drop_column('projects', 'owner_type')
    op.create_table('run_sheets',
    sa.Column('experiment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('protocol_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('graph', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('run_sheets_experiment_id_fkey')),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], name=op.f('run_sheets_protocol_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('run_sheets_pkey'))
    )
    op.drop_table('organization_members')
    op.drop_index('ix_objperm_principal', table_name='object_permissions')
    op.drop_index('ix_objperm_object', table_name='object_permissions')
    op.drop_table('object_permissions')
    # ### end Alembic commands ###
