"""add_revoked_offline_tokens

Revision ID: b7e75acf0874
Revises: 6081e54decae
Create Date: 2026-03-09 00:00:03.663389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7e75acf0874'
down_revision: Union[str, Sequence[str], None] = '6081e54decae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_offline_tokens',
    sa.Column('jti', sa.String(length=36), nullable=False, comment='JWT ID (jti) claim from the offline token'),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('revoked_by', sa.UUID(), nullable=False, comment='Admin user who revoked the token'),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['revoked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revoked_offline_tokens_jti'), 'revoked_offline_tokens', ['jti'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revoked_offline_tokens_jti'), table_name='revoked_offline_tokens')
    op.drop_table('revoked_offline_tokens')
    # ### end Alembic commands ###
