"""add is_draft to protocol_versions

Revision ID: ca5ce36de9cd
Revises: 4ffc79bc8a53
Create Date: 2026-03-05 19:49:06.686262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca5ce36de9cd'
down_revision: Union[str, Sequence[str], None] = '4ffc79bc8a53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('protocol_versions', sa.Column('is_draft', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('protocol_versions', 'is_draft')
    # ### end Alembic commands ###
