"""add tour_state and is_tour_sample flags [F-0015]

Revision ID: d17c2c930dee
Revises: 2a425e3691af
Create Date: 2026-04-17 23:52:26.866040

Note: this migration was originally autogenerated against a stale DB that
lacked the ``39ec554a844a`` / ``22cea73d75b4`` branch, so it re-created the
``experiments`` and ``invitations`` tables (plus ``runs.experiment_id`` and
``organization_members.archived``) that those ancestors already create. With
``down_revision`` pointed at the merge node ``2a425e3691af``, a from-scratch
``alembic upgrade head`` hit ``relation "experiments" already exists``. Those
duplicate ops have been removed; only the genuine F-0015 changes remain.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd17c2c930dee'
down_revision: Union[str, Sequence[str], None] = '2a425e3691af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column('ai_provider_configs', 'credentials',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_chunk_search_vector'), table_name='document_chunks', postgresql_using='gin')
    op.drop_column('document_chunks', 'search_vector')
    op.alter_column('document_templates', 'variables',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.add_column('protocols', sa.Column('is_tour_sample', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_protocols_is_tour_sample'), 'protocols', ['is_tour_sample'], unique=False)
    op.add_column('runs', sa.Column('is_tour_sample', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_runs_is_tour_sample'), 'runs', ['is_tour_sample'], unique=False)
    op.add_column('users', sa.Column('tour_state', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('users', 'tour_state')
    op.drop_index(op.f('ix_runs_is_tour_sample'), table_name='runs')
    op.drop_column('runs', 'is_tour_sample')
    op.drop_index(op.f('ix_protocols_is_tour_sample'), table_name='protocols')
    op.drop_column('protocols', 'is_tour_sample')
    op.alter_column('document_templates', 'variables',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.add_column('document_chunks', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english'::regconfig, content)", persisted=True), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_chunk_search_vector'), 'document_chunks', ['search_vector'], unique=False, postgresql_using='gin')
    op.alter_column('ai_provider_configs', 'credentials',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
