"""add tour_state and is_tour_sample flags [F-0015]

Revision ID: d17c2c930dee
Revises: 2a425e3691af
Create Date: 2026-04-17 23:52:26.866040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd17c2c930dee'
down_revision: Union[str, Sequence[str], None] = '2a425e3691af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiments',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invitations',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('invited_email', sa.String(), nullable=False),
    sa.Column('invited_user_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='PENDING', nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invited_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invitation_token', 'invitations', ['token'], unique=True)
    op.create_index('ix_pending_invitation', 'invitations', ['organization_id', 'invited_email'], unique=True, postgresql_where="status = 'PENDING'")
    op.alter_column('ai_provider_configs', 'credentials',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_chunk_search_vector'), table_name='document_chunks', postgresql_using='gin')
    op.drop_column('document_chunks', 'search_vector')
    op.alter_column('document_templates', 'variables',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.add_column('organization_members', sa.Column('archived', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('protocols', sa.Column('is_tour_sample', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_protocols_is_tour_sample'), 'protocols', ['is_tour_sample'], unique=False)
    op.add_column('runs', sa.Column('experiment_id', sa.UUID(), nullable=True))
    op.add_column('runs', sa.Column('is_tour_sample', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_runs_is_tour_sample'), 'runs', ['is_tour_sample'], unique=False)
    op.create_foreign_key(None, 'runs', 'experiments', ['experiment_id'], ['id'])
    op.add_column('users', sa.Column('tour_state', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tour_state')
    op.drop_constraint(None, 'runs', type_='foreignkey')
    op.drop_index(op.f('ix_runs_is_tour_sample'), table_name='runs')
    op.drop_column('runs', 'is_tour_sample')
    op.drop_column('runs', 'experiment_id')
    op.drop_index(op.f('ix_protocols_is_tour_sample'), table_name='protocols')
    op.drop_column('protocols', 'is_tour_sample')
    op.drop_column('organization_members', 'archived')
    op.alter_column('document_templates', 'variables',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.add_column('document_chunks', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english'::regconfig, content)", persisted=True), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_chunk_search_vector'), 'document_chunks', ['search_vector'], unique=False, postgresql_using='gin')
    op.alter_column('ai_provider_configs', 'credentials',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index('ix_pending_invitation', table_name='invitations', postgresql_where="status = 'PENDING'")
    op.drop_index('ix_invitation_token', table_name='invitations')
    op.drop_table('invitations')
    op.drop_table('experiments')
    # ### end Alembic commands ###
