"""f-0066 protocol approval

Revision ID: 51891425a0d0
Revises: 24f2759b7d74
Create Date: 2026-05-10 16:19:49.805399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0039_protocol_approval'
down_revision: Union[str, Sequence[str], None] = '24f2759b7d74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protocol_approval_requests',
    sa.Column('protocol_id', sa.UUID(), nullable=False),
    sa.Column('requested_user_id', sa.UUID(), nullable=True),
    sa.Column('requested_by_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='OPEN', nullable=False),
    sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fulfilled_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('OPEN','APPROVED','REJECTED','WITHDRAWN')", name='ck_proto_appr_req_status'),
    sa.ForeignKeyConstraint(['fulfilled_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_proto_appr_req_open_unique', 'protocol_approval_requests', ['protocol_id', 'requested_user_id'], unique=True, postgresql_where=sa.text("status = 'OPEN'"))
    op.create_table('protocol_approval_events',
    sa.Column('protocol_id', sa.UUID(), nullable=False),
    sa.Column('protocol_version_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('signature_statement', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('SUBMITTED','APPROVED','REJECTED','REVERTED')", name='ck_proto_appr_event_action'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['protocol_version_id'], ['protocol_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_proto_appr_event_protocol_created', 'protocol_approval_events', ['protocol_id', 'created_at'], unique=False)
    op.add_column('protocols', sa.Column('requires_approval', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('protocols', sa.Column('created_by_id', sa.UUID(), nullable=True))
    op.add_column('protocols', sa.Column('approved_by_id', sa.UUID(), nullable=True))
    op.add_column('protocols', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key('fk_protocols_approved_by_id', 'protocols', 'users', ['approved_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_protocols_created_by_id', 'protocols', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.add_column('runs', sa.Column('is_strict', sa.Boolean(), server_default='false', nullable=False))
    op.drop_index(op.f('ix_users_oauth_provider'), table_name='users')
    # ### end Alembic commands ###

    # Backfill protocols.created_by_id from v1 ProtocolVersion creator.
    op.execute("""
        UPDATE protocols p
        SET created_by_id = pv.created_by_id
        FROM protocol_versions pv
        WHERE pv.protocol_id = p.id
          AND pv.version_number = (
              SELECT MIN(version_number) FROM protocol_versions WHERE protocol_id = p.id
          )
          AND pv.created_by_id IS NOT NULL
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_oauth_provider'), 'users', ['oauth_provider'], unique=False)
    op.drop_column('runs', 'is_strict')
    op.drop_constraint('fk_protocols_approved_by_id', 'protocols', type_='foreignkey')
    op.drop_constraint('fk_protocols_created_by_id', 'protocols', type_='foreignkey')
    op.drop_column('protocols', 'approved_at')
    op.drop_column('protocols', 'approved_by_id')
    op.drop_column('protocols', 'created_by_id')
    op.drop_column('protocols', 'requires_approval')
    op.drop_index('ix_proto_appr_event_protocol_created', table_name='protocol_approval_events')
    op.drop_table('protocol_approval_events')
    op.drop_index('ix_proto_appr_req_open_unique', table_name='protocol_approval_requests', postgresql_where=sa.text("status = 'OPEN'"))
    op.drop_table('protocol_approval_requests')
    # ### end Alembic commands ###
