"""add rate limit and notification tables

Revision ID: f231e81290bd
Revises: d17c2c930dee
Create Date: 2026-04-18 22:58:01.643011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f231e81290bd'
down_revision: Union[str, Sequence[str], None] = 'd17c2c930dee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_rate_limit_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_key_attempted_at', 'chat_rate_limit_attempts', ['key', 'attempted_at'], unique=False)
    op.create_table('chat_notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_org_created_at', 'chat_notifications', ['org_id', 'created_at'], unique=False)
    op.create_index('idx_user_created_at', 'chat_notifications', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_created_at', table_name='chat_notifications')
    op.drop_index('idx_org_created_at', table_name='chat_notifications')
    op.drop_table('chat_notifications')
    op.drop_index('idx_key_attempted_at', table_name='chat_rate_limit_attempts')
    op.drop_table('chat_rate_limit_attempts')
    # ### end Alembic commands ###
