"""Transitional shim (TD-0083) — re-exports the split `science` schemas.

Deleted once all imports migrate to the domain modules. Import from
`app.schemas.protocols` / `.runs` / `.signoffs` instead.
"""

from app.schemas.protocols import (
    ApprovalActorRef,
    ApproveProtocolRequest,
    AwaitingApprovalItem,
    DesignateApprovalRequest,
    GraphPayload,
    ProtocolBase,
    ProtocolCreate,
    ProtocolImportFinalizeRequest,
    ProtocolImportProposalResponse,
    ProtocolRefineRequest,
    ProtocolResponse,
    ProtocolRoleBase,
    ProtocolRoleCreate,
    ProtocolRoleResponse,
    ProtocolRoleUpdate,
    ProtocolUpdate,
    ProtocolVersionListItem,
    ProtocolVersionResponse,
    PublishDraftRequest,
    RejectProtocolRequest,
    StepProposalSchema,
    SubmitForApprovalRequest,
    UnitOpDefinitionBase,
    UnitOpDefinitionCreate,
    UnitOpDefinitionResponse,
    UnitOpDefinitionUpdate,
)
from app.schemas.runs import (
    CheckLotNumberResponse,
    ExperimentCreate,
    ExperimentNote,
    ExperimentNoteCreate,
    ExperimentNoteListResponse,
    ExperimentResponse,
    ExperimentStatus,
    ExperimentUpdate,
    NodeOverrides,
    RunAttachment,
    RunAttachmentListResponse,
    RunBase,
    RunCompleteRequest,
    RunCreate,
    RunNote,
    RunNoteCreate,
    RunNoteListResponse,
    RunOverrides,
    RunReopenRequest,
    RunResponse,
    RunRoleAssignmentBase,
    RunRoleAssignmentCreate,
    RunRoleAssignmentListResponse,
    RunRoleAssignmentResponse,
    RunStateUpdate,
    RunStatus,
    RunStepStateUpdate,
    RunUpdate,
    SuggestLotNumberRequest,
    SuggestLotNumberResponse,
)
from app.schemas.signoffs import GlpSignoffCreate, GlpSignoffResponse

__all__ = [
    # protocols
    "ApprovalActorRef",
    "ApproveProtocolRequest",
    "AwaitingApprovalItem",
    "DesignateApprovalRequest",
    "GraphPayload",
    "ProtocolBase",
    "ProtocolCreate",
    "ProtocolImportFinalizeRequest",
    "ProtocolImportProposalResponse",
    "ProtocolRefineRequest",
    "ProtocolResponse",
    "ProtocolRoleBase",
    "ProtocolRoleCreate",
    "ProtocolRoleResponse",
    "ProtocolRoleUpdate",
    "ProtocolUpdate",
    "ProtocolVersionListItem",
    "ProtocolVersionResponse",
    "PublishDraftRequest",
    "RejectProtocolRequest",
    "StepProposalSchema",
    "SubmitForApprovalRequest",
    "UnitOpDefinitionBase",
    "UnitOpDefinitionCreate",
    "UnitOpDefinitionResponse",
    "UnitOpDefinitionUpdate",
    # runs
    "CheckLotNumberResponse",
    "ExperimentCreate",
    "ExperimentNote",
    "ExperimentNoteCreate",
    "ExperimentNoteListResponse",
    "ExperimentResponse",
    "ExperimentStatus",
    "ExperimentUpdate",
    "NodeOverrides",
    "RunAttachment",
    "RunAttachmentListResponse",
    "RunBase",
    "RunCompleteRequest",
    "RunCreate",
    "RunNote",
    "RunNoteCreate",
    "RunNoteListResponse",
    "RunOverrides",
    "RunReopenRequest",
    "RunResponse",
    "RunRoleAssignmentBase",
    "RunRoleAssignmentCreate",
    "RunRoleAssignmentListResponse",
    "RunRoleAssignmentResponse",
    "RunStateUpdate",
    "RunStatus",
    "RunStepStateUpdate",
    "RunUpdate",
    "SuggestLotNumberRequest",
    "SuggestLotNumberResponse",
    # signoffs
    "GlpSignoffCreate",
    "GlpSignoffResponse",
]
